CREATE TABLE IF NOT EXISTS artists (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL UNIQUE,
  stage_name VARCHAR(150) NOT NULL,
  full_name VARCHAR(150) NULL,
  first_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  image VARCHAR(255) NULL,
  birth_date DATE NULL,
  height VARCHAR(50) NULL,
  weight VARCHAR(50) NULL,
  partner_name VARCHAR(150) NULL,
  partner_artist_id INT NULL,
  mascot VARCHAR(150) NULL,
  artist_role VARCHAR(100) NULL,
  description TEXT NULL,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('active', 'hidden') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_artists_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_artists_partner FOREIGN KEY (partner_artist_id) REFERENCES artists(id) ON DELETE SET NULL,
  INDEX idx_artists_stage_name (stage_name),
  INDEX idx_artists_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
